services:
  x86:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /srv:/srv
    environment:
      - ARCH=x86
    hostname: kbuild
    tty: true

  arm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /srv:/srv
    environment:
      - ARCH=arm
      - CROSS_COMPILE=arm-linux-gnueabihf-
      - KERNEL=kernel7l
    hostname: kbuild
    tty: true

  arm64:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /srv:/srv
    environment:
      - ARCH=arm64
      - CROSS_COMPILE=aarch64-linux-gnu-
      - KERNEL=kernel8
    hostname: arm64
    tty: true
